@startuml
skinparam classAttributeIconSize 0

class ClassUML {
  +name : {Id} String
  +isAbstract : Boolean
  +isInterface : Boolean
}


ClassUML "1" o-- "*" Attribute
ClassUML "1" o-- "*" Operation


class Attribute {
  +name : {Id} String
  +type : Type
  +visibility : String
}


class Operation {
  +name : {Id}
  +returnType : Type
  +visibility : String
}

class Relation {
  +type : RelationType
  +cardSource : Int
  +cardTarget : Int 
}

Relation "2"--> "2" ClassUML : "{ Ordonné avec source au début et target à la fin en deuxiéme }"
Relation "0..*" o-- "1" Cardinality : sourceCardinality
Relation "0..*" o-- "1" Cardinality : targetCardinality

abstract class Class { 
  + generate()
}

Class <|--  ClassUML
Class <|-- "ClassC++"
Class <|-- ClassJava
Class <|-- ClassPython


class ClassJava{}
class ClassC++{}
class ClassPython{}

class Type {
  +name : String
}

class Notes{
 +emplacement : int 
 +contenu : String
} 	

@enduml

