@startuml
skinparam classAttributeIconSize 0

class Class {
  +name : Identifier
  +isAbstract : Boolean
  +isInterface : Boolean
}

Class "1" o-- "*" Attribute
Class "1" o-- "*" Operation


class Attribute {
  +name : Identifier
  +type : Type
  +visibility : Visibility
}


class Operation {
  +name : Identifier
  +returnType : Type
  +visibility : Visibility
}

class Relation {
  +type : RelationType
}

Relation "1" --> "1" Class : source
Relation "1" --> "1" Class : target
Relation "1" o-- "1" Cardinality : sourceCardinality
Relation "1" o-- "1" Cardinality : targetCardinality


class Cardinality {
  +value : String
}

class Identifier {
  +value : String
}

class Type {
  +name : String
}

class Notes{
 +emplacement : int 
 +contenu : String
} 	

@enduml

