@startuml
skinparam classAttributeIconSize 0

class Class {
  +name : {Id} String
  +isAbstract : Boolean
  +isInterface : Boolean
}

Class "1" o-- "*" Attribute
Class "1" o-- "*" Operation


class Attribute {
  +name : {Id} String
  +type : Type
  +visibility : String
}


class Operation {
  +name : {Id}
  +returnType : Type
  +visibility : String
}

class Relation {
  +type : RelationType
}

Relation "1" --> "1" Class : source
Relation "1" --> "1" Class : target
Relation "0..*" o-- "1" Cardinality : sourceCardinality
Relation "0..*" o-- "1" Cardinality : targetCardinality

abstract class Langage { 
  + generate()
}

class Cardinality {
  +value : Int
}

class ClasseJava{}
class ClasseC++{}
class ClasseRust{}

class Type {
  +name : String
}

class Notes{
 +emplacement : int 
 +contenu : String
} 	

@enduml

