@startuml
title UMLFactory2Code - Extension C++
skinparam classAttributeIconSize 0

' --- Rappel du contexte commun ---
package "Contexte Commun" {

  abstract class Generateur {
    +langage : {ID} LangageSortie
    ---
    +genererClasse2Langage(DiagrammeClasse) : List<File>
    +genererBlocCommentaire() : String
  }

  enum LangageSortie {
    CPP
    PYTHON
    JAVA
  }
  class Formattage {
    +idFormattage : {ID} String
    ---
    +genererCode()
  }
}

package "Extension C++" #LightBlue {

  ' --- GenerateurCpp ---
  class GenerateurCpp {
    +langage : {ID} LangageSortie = CPP
    ---
    +genererClasse2Langage(DiagrammeClasse) : List<FichierCpp>
    +genererBlocCommentaire() : String
    +genererCode() : String
    -traduireClasse(UMLClasse) : ClasseCpp
    -traduireRelation(ClasseCpp, String, Relation, Map) : void
    -genererHeader(ClasseCpp) : FichierCpp
    -genererSource(ClasseCpp) : FichierCpp
  }

  note left of GenerateurCpp::genererClasse2Langage
    Polymorphisme par specialisation
  end note

  ' --- FichierCpp ---
  class FichierCpp {
    +nomFichier : {ID} String
    +typeFichier : TypeFichierCpp
    +cheminComplet : String
    ---
    +genererCode() : String
    +sauvegarder() : void
  }

  note bottom of FichierCpp
    <b>Delegation :</b>
    genererCode() appelle
    ClasseCpp.genererCode()
  end note

  ' --- ClasseCpp ---
  class "Classe" as ClasseCpp {
    +nom : {ID} String
    +estAbstraite : Boolean
    -notes : List<String>
    -attributsCpp : List<AttributCpp>
    -operationsCpp : List<OperationCpp>
    -relationsCpp : List<RelationCpp>
    ---
    +genererCode() : String
    +getAttributsCpp() : List<AttributCpp>
    +getOperationsCpp() : List<OperationCpp>
  }

  ' --- AttributCpp ---
  class AttributCpp {
    +nom : {ID} String
    +typeCpp : String
    +estConst : Boolean
    +estStatic : Boolean
    ---
    +genererCode() : String
  }

  ' --- OperationCpp ---
  class OperationCpp {
    +nom : {ID} String
    +typeRetourCpp : String
    +estVirtuelle : Boolean
    +estVirtuellePure : Boolean
    ---
    +genererCode() : String
  }

  ' --- RelationCpp ---
  class RelationCpp {
    +idRelation : {ID} String
    +typeRelation : TypeRelationCpp
    ---
    +genererCode() : String
    +genererInclude() : String
  }

  class RelationCppAvecCardinalite {
    +idRelation : String
    +typeRelation : TypeRelationCpp
    +cardinaliteSource : String
    +cardinaliteSource : String
    +roleSource : String
    +roleCible : String
    ---
    +genererCode() : String
    +genererInclude() : String
  }

  ' --- Implementation ---
  class RelationCppSansCardinalite {
    +idRelation : String
    +typeRelation : TypeRelationCpp
    ---
    +genererCode() : String
    +genererInclude() : String
  }


  ' --- Enums ---
  enum TypeFichierCpp {
    HEADER
    SOURCE
  }

  enum TypeRelationCpp {
    ASSOCIATION
    AGREGATION
    HERIATGE 
    IMPLEMENTATION
  }

  ' ===== RELATIONS =====

  Formattage ..|> ClasseCpp
  Formattage ..|> OperationCpp
  Formattage ..|> AttributCpp
  Formattage ..|> RelationCpp
  Formattage ..|> FichierCpp
  ' Heritage vers le commun
  Generateur <|-- GenerateurCpp

  ' Heritage local
  RelationCpp <|-- RelationCppSansCardinalite
  RelationCpp <|-- RelationCppAvecCardinalite 


  ' Agregation : le generateur cree des fichiers
  GenerateurCpp "1" o-- "0..*" FichierCpp 

  ' Agregation : un fichier contient des classes
  FichierCpp "1" o-- "1..*" ClasseCpp 

  ' Composition : une classe possede ses attributs et operations
  ClasseCpp "1" *-- "0..*" AttributCpp
  ClasseCpp "1" *-- "0..*" OperationCpp 

  ' Agregation : une relation lie 2 classes
  ClasseCpp "2" o-- "0..*" RelationCpp 

  ' Associations vers enums
  FichierCpp ..> TypeFichierCpp
  RelationCpp ..> TypeRelationCpp
}

@enduml
